### ISSUE TITLE
call make in makefile

### ISSUE THREAD

**Issue by x86poem** [kmc7468/setaria#1]
isn't it 
$(MAKE) -C ...
instead of 
make -C ...?

**Comment by kmc7468** [comment]
한국인이신 것 같으므로 한국어로 작성하겠습니다.
makefile을 이번에 처음 쓰는거라 그런게 가능한지 몰랐습니다. 다음 커밋에서 반영하도록 하겠습니다. 감사합니다.

**Comment by x86poem** [comment]
넵

**Comment by RanolP** [comment]
@kmc7468 엌ㅋ
